name: test
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    name: Test code
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

        go-version:
          - stable
          - "" # empty string = read version from go.mod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: "go.mod"
          cache: false
          check_latest: true

      - name: "Go test"
        runs: "go test ./..."
